### ISSUE TITLE
Error Cannot Find Bundler

### ISSUE THREAD

**Issue by murpg** [madhur/PortableJekyll#28]
I get this error when I try and run from Windows 8.1 thumb drive.  
```
F:/PortableJekyll-master/ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:106:in `require': cannot load such file -- bundler (LoadError)
        from F:/PortableJekyll-master/ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:106:in `require'
        from F:/PortableJekyll-master/ruby/lib/ruby/gems/2.0.0/gems/jekyll-3.2.1/lib/jekyll/plugin_manager.rb:34:in `require_from_bundler'
        from F:/PortableJekyll-master/ruby/lib/ruby/gems/2.0.0/gems/jekyll-3.2.1/exe/jekyll:9:in `<top (required)>'
        from F:/PortableJekyll-master/ruby/bin/jekyll:23:in `load'
        from F:/PortableJekyll-master/ruby/bin/jekyll:23:in `<main>'
```

**Comment by shahamit** [comment]
Yes, I get the same on Windows 10 too.

**Comment by hmqq** [comment]
I am also getting the same error.
